apiVersion: apps/v1
kind: Deployment 
metadata:
  name: java-example
spec:
  selector:
    matchLabels:
      app: java-example
  replicas: 2 
  template:
    metadata:
      labels:
        app: java-example
    spec:
      serviceAccountName: yaqoob-new
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: java-example
          image: 140023400586.dkr.ecr.ap-south-1.amazonaws.com/dec-2025:AB1
          command: ["/bin/sh", "-c", "sleep infinity"]
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: java-example-service
spec:
  selector:
    app: java-example
  type: NodePort
  ports:
    - protocol: TCP
      port: 80  # Service port
      targetPort: 80  # Container port
      nodePort: 30080  # NodePort 

